### ISSUE TITLE
simple-build-dgcode installed but dgcode bundle not found

### ISSUE THREAD

**Issue by MilanKlausz** [mctools/simplebuild#46]
In short:
_simple-build-system_ versions from 0.0.25 to 0.0.36 can't find _dgcode_ as a dependency eventhough the _simple-build-dgcode_ package is installed.

Longer version:
I've tried to use _dgcode_projects_ with different version of the _simple-build-system_ and _simple-build-dgcode_. I've found that I can only build the packages using a _simple-build-system_ that is older than version 0.0.25. 
The actual error message when trying to use _sb_  is:
` ERROR: Could not find dependent project: "dgcode"`

The version of _simple-build-dgcode_ (from 0.0.1 to 0.0.3) doesn't seem to matter. 
The [change from v0.0.24 to v0.0.25](https://github.com/mctools/simplebuild/compare/v0.0.24...v0.0.25) included "_Change py-plugin search pattern_", so that could be the source of the problem.

The environment was created with:
```
name: dgcode
channels:
  - nodefaults
  - conda-forge
dependencies:
  - compilers
  - bash
  - simple-build-system
  - ncrystal
  - matplotlib
  - zlib
  - geant4
  - expat
  - openscenegraph
  - scipy
  - hdf5
  - pysimplegui
  - pip
  - pip:
    - simple-build-dgcode
```
The version of the packages were changed with:
`pip install --force-reinstall -v "simple-build-system==0.0.25"`

**Comment by tkittel** [comment]
Ah yes, this is simply because the simple-build-dgcode package is not yet ready for usage (as the documentation says, "DO NOT USE YET!" :-) ). Please only use the latest simple-build-system package (I.e. reinstall the latest, currently v0.0.36), and wait ~a few days for the simple-build-dgcode package to have a new version.

In the meantime, if you are brave, you can try to use the tk_volatile branch of simple-build-dgcode, which should in principle work (although it is... you guessed it... volatile).

Maybe a command like:

```
python3 -mpip install git+https://github.com/mctools/simplebuild-dgcode@tk_volatile
```

**Comment by tkittel** [comment]
You can now install from main as well, I am currently debugging the pypi deployment so the pypi packages are still still on the old.

**Comment by tkittel** [comment]
Ok, it is working! Now please make sure you use the latest simple-build-system (0.0.36) and the latest simple-build-dgcode (0.0.6) packages, and I believe it should just work!
